### ISSUE TITLE
DesenhaContornos

### ISSUE THREAD

**Issue by RafaelCamarda** [ayusuke7/OpencvPython#1]
Essa versão do DesenhaContornos está completa? Ela me parece diferente da versão mostrada no vídeo.

**Comment by ayusuke7** [comment]
No caso do Video os único Scripts utilizados ~são o EncontrarPlaca e EncontrarPlacaHD mudando apenas a entrada que no caso são videos 480p e 720p. Muitas pessoas me perguntam sobre o programa eu disponibilizei o codigo base que são esses 2 e no meu site o livro Python e OpenCV na qual foi retirado o conteudo necessario. Não apenas copiem o codigo vejam o funionamento da função e como ela se comporta que com o basico conseguirá utilizar o Reconhecimento por Retangulos.

Boa Sorte!
